create table if not exists CUSTOMER (
	PHONENO VARCHAR(10),
	NAME VARCHAR(45) NOT NULL,
	ADDRESS VARCHAR(45) NOT NULL,
	ZIPCODE VARCHAR(5) NOT NULL,
	primary key (PHONENO)
);

create table if not exists EMPLOYEE (
	EMPLOYEEID NUMBER(38,0) AUTO_INCREMENT,
	ACTIVESTATUS VARCHAR(45) NOT NULL,
	NAME VARCHAR(45) NOT NULL,
	primary key (EMPLOYEEID)
);

create table if not exists PRODUCT (
	PRODUCTID NUMBER(38,0) AUTO_INCREMENT,
	NAME VARCHAR(45) NOT NULL,
	PRICE NUMBER(9,2) NOT NULL,
	primary key (PRODUCTID)
);

create table if not exists CUSTOMER_ORDER (
	CUSTOMER_ORDER NUMBER(38,0) AUTO_INCREMENT,
	PHONENO VARCHAR(10) NOT NULL,
	EMPLOYEEID NUMBER(38,0) NOT NULL,
	primary key (CUSTOMER_ORDER),
	foreign key (PHONENO) references CUSTOMER(PHONENO)
);

create table if not exists ORDER_DETAILS (
	ORDER_NUMBER NUMBER(38,0) AUTO_INCREMENT,
	CUSTOMER_ORDER NUMBER(38,0) NOT NULL,
	TOTALPRICE NUMBER(9,2) NOT NULL,
	TIME DATETIME NOT NULL,
	primary key (ORDER_NUMBER),
	foreign key (CUSTOMER_ORDER) references CUSTOMER_ORDER(CUSTOMER_ORDER)
);

create table if not exists ORDER_LIST (
	ORDER_INDEX NUMBER(38,0) AUTO_INCREMENT,
	ORDER_NUMBER NUMBER(38,0) NOT NULL,
	PRODUCTID VARCHAR(9) NOT NULL,
	QUANTITY NUMBER(38,0) NOT NULL,
	primary key (ORDER_INDEX),
	foreign key (PRODUCTID) references PRODUCT(PRODUCTID)
);